Repository WildCodeSchool/2023-03-JS-TLSE-P2-mytouloulist, pull requests merged in 2023-05, with the labels that each got.

#37 Project styling improvements
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/ApplyButton.css
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
  frontend/src/components/FiltersMenu.css
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/Footer.css
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  frontend/src/components/PlaceEventsMenu.css
  frontend/src/components/PrimaryCheckboxButton.css
  frontend/src/components/PrimaryCheckboxButton.jsx
  frontend/src/components/TagsFilter.css
  frontend/src/components/TagsFilter.jsx
Labels: Reviewed

#36 S04 us21 navbar filters display
  frontend/src/App.jsx
  frontend/src/components/ApplyButton.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/PrimaryCheckboxButton.jsx
Labels: Reviewed

#40 linted and resolved conflict, apply_button sets to false the home pag…
  frontend/src/App.jsx
  frontend/src/components/ApplyButton.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/PrimaryCheckboxButton.jsx
Labels: Reviewed

#41 solved issue of clicked_unclicked primary buttons remaining clicked a…
  frontend/src/App.jsx
  frontend/src/components/ApplyButton.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/NavBar.jsx
Labels: Reviewed

#42 S04 us21 navbar filters display
  frontend/src/App.jsx
  frontend/src/components/ApplyButton.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/PrimaryCheckboxButton.jsx
Labels: Reviewed

#45 S04 us19 sorting menu
  frontend/index.html
  frontend/public/assets/favicon.ico
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/ApplyButton.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/PrimaryCheckboxButton.css
  frontend/src/components/PrimaryCheckboxButton.jsx
  frontend/src/components/SortingMenu.css
  frontend/src/components/SortingMenu.jsx
Labels: Reviewed

#44 S04 to top button
  frontend/public/assets/toTopButton.png
  frontend/src/App.jsx
  frontend/src/components/ScrollToTopButton.css
  frontend/src/components/ScrollToTopButton.jsx
Labels: Conflicts resolved

#46 S04 us21 navbar filters display
  frontend/src/App.jsx
  frontend/src/components/ApplyButton.jsx
  frontend/src/components/DateFilter.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  frontend/src/components/PrimaryCheckboxButton.jsx
Labels: Reviewed

#47 Fixed desktop CSS
  frontend/src/components/DateFilter.css
  frontend/src/components/DateFilter.jsx
Labels: Reviewed

#48 S04 us17 creation modal at clic on card
  frontend/src/App.jsx
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
Labels: Reviewed, Corrections done

#49 S04 US23 modal in button about us
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
Labels: Reviewed

#50 S04 us04 map
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/assets/List.png
  frontend/public/assets/Map.png
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Card.css
  frontend/src/components/Footer.css
  frontend/src/components/Map.css
  frontend/src/components/Map.jsx
  package-lock.json
  package.json
Labels: Reviewed, Corrections done

#52 Project styling improvements
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/DateFilter.css
  frontend/src/components/DateFilter.jsx
  frontend/src/components/FiltersMenu.css
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/Footer.css
  frontend/src/components/NavBar.jsx
  frontend/src/components/PlaceEventsMenu.css
  frontend/src/components/PlaceEventsMenu.jsx
  frontend/src/components/PrimaryCheckboxButton.css
  frontend/src/components/PrimaryCheckboxButton.jsx
  frontend/src/components/ScrollToTopButton.css
  frontend/src/components/ScrollToTopButton.jsx
  frontend/src/components/SortingMenu.css
  frontend/src/components/SortingMenu.jsx
  frontend/src/components/SportCultureMenu.css
  frontend/src/components/SportCultureMenu.jsx
Labels: Reviewed

#53 S04 us04 map
  frontend/index.html
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/CustomPopup.jsx
  frontend/src/components/Map.jsx
Labels: Reviewed

#54 S04 us04 map button
  frontend/public/assets/List_chosen.png
  frontend/public/assets/Map_chosen.png
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Card.jsx
  frontend/src/components/FiltersMenu.css
Labels: Reviewed

#55 S04 card modal improvements
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
Labels: Reviewed

#56 S04 us04 map
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/CustomPopup.css
  frontend/src/components/CustomPopup.jsx
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
  frontend/src/components/Map.css
  frontend/src/components/PlaceEventsMenu.css
Labels: Reviewed

#57 S04 fix the style card and responsive
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
Labels: Reviewed

#58 S04 error page display
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Error.css
  frontend/src/components/Error.jsx
Labels: Reviewed

#60 Fixed Map button
  frontend/src/App.css
  frontend/src/App.jsx
Labels: Reviewed

#59 about us text shortened
  frontend/src/components/Footer.jsx
Labels: Reviewed

#61 S04 fix modal card style
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/CustomPopup.css
  frontend/src/components/CustomPopup.jsx
Labels: Reviewed

#62 S04 fix style mobile
  frontend/src/App.jsx
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
Labels: Reviewed

#63 Hotfixes
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Card.css
Labels: Reviewed

#65 Fixed images map button
  frontend/src/App.css
Labels: Reviewed

#67 hotfixed filter menu
  frontend/src/components/FiltersMenu.css
Labels: Reviewed

#68 Dev
  frontend/src/components/FiltersMenu.css
Labels: Reviewed
