Repository WildCodeSchool/2023-03-JS-TLSE-P2-mytouloulist, pull requests merged in 2023-04, with the labels that each got.

#1 Fetch api
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  package-lock.json
  package.json
Labels: Reviewed

#2 Dev
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  package-lock.json
  package.json
Labels: Reviewed

#4 S02 us13 primary checkbox button
  .env
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/header_icons/culture.png
  frontend/src/assets/header_icons/culture_clicked.png
  frontend/src/assets/header_icons/sport.png
  frontend/src/assets/header_icons/sport_clicked.png
  frontend/src/components/PrimaryCheckboxButton.jsx
  package.json
  pnpm-lock.yaml
Labels: Reviewed

#5 S02US10_map all unfiltered card
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/cinema.png
  frontend/src/assets/events.png
  frontend/src/assets/stadium.png
  frontend/src/components/Card.jsx
  frontend/src/components/PrimaryCheckboxButton.jsx
  package-lock.json
  package.json
Labels: Reviewed, Corrections done

#6 S02 Added calendar
  frontend/src/App.jsx
  frontend/src/components/Counter.jsx
  frontend/src/components/DateFilter.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/pages/Home.jsx
Labels: Reviewed

#8 Delete Home.jsx
  frontend/src/pages/Home.jsx
Labels: Reviewed

#7 Dev
  .env
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/cinema.png
  frontend/src/assets/events.png
  frontend/src/assets/header_icons/culture.png
  frontend/src/assets/header_icons/culture_clicked.png
  frontend/src/assets/header_icons/sport.png
  frontend/src/assets/header_icons/sport_clicked.png
  frontend/src/assets/stadium.png
  frontend/src/components/Card.jsx
  frontend/src/components/Counter.jsx
  frontend/src/components/DateFilter.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/PrimaryCheckboxButton.jsx
  frontend/src/pages/Home.jsx
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: Reviewed

#10 S02 us13 primary checkbox button toggle improvements
  frontend/src/App.css
  frontend/src/components/PrimaryCheckboxButton.css
  frontend/src/components/PrimaryCheckboxButton.jsx
Labels: Reviewed

#9 S02 us10 nav bar
  frontend/index.html
  frontend/normalize.css
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/filter_icon.png
  frontend/src/assets/myLogo.png
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  package.json
  pnpm-lock.yaml
Labels: Conflicts resolved

#12 S02US10_Navbar
  frontend/src/components/NavBar.css
Labels: Reviewed

#14 S02 us12 main filter
  frontend/src/App.jsx
  frontend/src/components/Card.jsx
  frontend/src/components/DateFilter.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/PlaceEventsMenu.jsx
  frontend/src/components/SportCultureMenu.jsx
Labels: Corrections done

#15 S03 us18 tags filter
  frontend/src/App.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/TagsFilter.css
  frontend/src/components/TagsFilter.jsx
Labels: Reviewed

#17 S03 us18 tags filter
  frontend/src/App.jsx
  frontend/src/components/TagsFilter.jsx
Labels: Reviewed

#20 S03US16_add responsive card display
  frontend/src/App.css
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
Labels: Reviewed

#19 S03 us22 footer
  frontend/src/App.jsx
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
  package-lock.json
  package.json
Labels: Reviewed

#21 S03 us15 apply button operational
  frontend/src/App.css
  frontend/src/components/ApplyButton.css
  frontend/src/components/ApplyButton.jsx
  frontend/src/components/Card.css
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/TagsFilter.jsx
Labels: Reviewed

#23 S03US11 creation button en savoir plus in all cards
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
Labels: Reviewed

#24 S03 us12 style filter menu
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/close_icon.svg
  frontend/src/components/ApplyButton.jsx
  frontend/src/components/FiltersMenu.css
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  frontend/src/components/PlaceEventsMenu.css
  frontend/src/components/PlaceEventsMenu.jsx
Labels: Reviewed

#26 S03 Corrected Netlify images bug
  frontend/public/_redirects
  frontend/public/assets/.gitkeep
  frontend/public/assets/cinema.png
  frontend/public/assets/close_icon.svg
  frontend/public/assets/events.png
  frontend/public/assets/favicon.svg
  frontend/public/assets/filter_icon.png
  frontend/public/assets/header_icons/culture.png
  frontend/public/assets/header_icons/culture_clicked.png
  frontend/public/assets/header_icons/sport.png
  frontend/public/assets/header_icons/sport_clicked.png
  frontend/public/assets/logo.svg
  frontend/public/assets/myLogo.png
  frontend/public/assets/stadium.png
  frontend/src/components/Card.jsx
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/PrimaryCheckboxButton.jsx
  frontend/src/components/SportCultureMenu.jsx
Labels: Reviewed

#25 styling improvements in navbar display, reducing fonts and arranging …
  frontend/src/components/NavBar.css
Labels: Reviewed

#27 Dev
  frontend/index.html
  frontend/normalize.css
  frontend/public/_redirects
  frontend/public/assets/.gitkeep
  frontend/public/assets/cinema.png
  frontend/public/assets/close_icon.svg
  frontend/public/assets/events.png
  frontend/public/assets/favicon.svg
  frontend/public/assets/filter_icon.png
  frontend/public/assets/header_icons/culture.png
  frontend/public/assets/header_icons/culture_clicked.png
  frontend/public/assets/header_icons/sport.png
  frontend/public/assets/header_icons/sport_clicked.png
  frontend/public/assets/logo.svg
  frontend/public/assets/myLogo.png
  frontend/public/assets/stadium.png
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/ApplyButton.css
  frontend/src/components/ApplyButton.jsx
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
  frontend/src/components/DateFilter.jsx
  frontend/src/components/FiltersMenu.css
  frontend/src/components/FiltersMenu.jsx
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  frontend/src/components/PlaceEventsMenu.css
  frontend/src/components/PlaceEventsMenu.jsx
  frontend/src/components/PrimaryCheckboxButton.css
  frontend/src/components/PrimaryCheckboxButton.jsx
  frontend/src/components/SportCultureMenu.jsx
  frontend/src/components/TagsFilter.css
  frontend/src/components/TagsFilter.jsx
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: Reviewed

#29 TagsFilter button design
  frontend/src/components/TagsFilter.css
  frontend/src/components/TagsFilter.jsx
Labels: Reviewed

#28 S03 all styling improvements
  frontend/index.html
  frontend/src/components/ApplyButton.css
  frontend/src/components/NavBar.css
  frontend/src/components/PrimaryCheckboxButton.css
  frontend/src/components/PrimaryCheckboxButton.jsx
Labels: Reviewed

#30 Dev
  frontend/index.html
  frontend/src/components/ApplyButton.css
  frontend/src/components/NavBar.css
  frontend/src/components/PrimaryCheckboxButton.css
  frontend/src/components/PrimaryCheckboxButton.jsx
  frontend/src/components/TagsFilter.css
  frontend/src/components/TagsFilter.jsx
Labels: Reviewed

#31 S0US16 responsive card fixed
  frontend/src/components/Card.css
  frontend/src/components/Card.jsx
Labels: Reviewed

#32 S03 us15 apply button
  frontend/src/components/ApplyButton.jsx
Labels: Reviewed
